[package]
name = "ui"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[dependencies]
bitflags = "0.7"
libc = "*"
ui-sys = { path = "ui-sys" }

[workspace]
members = [".", "ui-sys"]


